matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install --user https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
