language: python
python:
  - 2.7
  - 3.3
sudo: false

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
  
script:
  - pip install numpy
  - pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse
